/* ============================================================
 * KODNEST CAREERS — JOB DATASET v1.0
 * 60 realistic Indian tech jobs — static seed data
 * ============================================================ */

window.JOBS = [
  {
    id: 1,
    title: "Graduate Engineer Trainee",
    company: "Infosys",
    location: "Mysuru",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "SQL", "Data Structures", "Problem Solving"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "3.6 LPA",
    applyUrl: "https://www.linkedin.com/jobs/view/3812547001",
    description: "Infosys is hiring Graduate Engineer Trainees for its Global Education Centre in Mysuru. Selected candidates undergo a rigorous 5-month residential training covering Java, databases, and software engineering principles. Post-training, you will be deployed to a client project team based on performance. A stipend is paid during training, and the confirmed package begins post-deployment. This is a structured launchpad for engineers beginning their careers in enterprise software."
  },
  {
    id: 2,
    title: "SDE Intern",
    company: "Infosys",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "REST APIs", "Git", "Linux"],
    source: "Naukri",
    postedDaysAgo: 3,
    salaryRange: "₹20k–₹35k/month",
    applyUrl: "https://www.naukri.com/job-listings/sde-intern-infosys-bangalore-3112847002",
    description: "Infosys offers a 6-month SDE internship at its Bangalore campus where interns work on live product modules under senior engineering mentorship. You will participate in sprint planning, code reviews, and delivery cycles. Interns with strong performance are considered for full-time offers. Exposure to Python or JavaScript is preferred. The role is hybrid — three days in office per week."
  },
  {
    id: 3,
    title: "Data Analyst Intern",
    company: "Infosys",
    location: "Pune",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Excel", "SQL", "Power BI", "Python"],
    source: "LinkedIn",
    postedDaysAgo: 5,
    salaryRange: "₹18k–₹30k/month",
    applyUrl: "https://www.linkedin.com/jobs/view/3812547003",
    description: "Infosys Pune is looking for Data Analyst Interns to join its analytics delivery team. You will assist in data cleaning, dashboard creation, and report generation for enterprise clients across BFSI and retail verticals. Familiarity with SQL and Excel is expected; Power BI experience is a plus. The internship runs for 6 months and is a strong entry point into data roles at scale."
  },
  {
    id: 4,
    title: "Graduate Engineer Trainee",
    company: "TCS",
    location: "Chennai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["C", "Java", "DBMS", "Aptitude"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "3.36 LPA",
    applyUrl: "https://www.linkedin.com/jobs/view/3812547004",
    description: "TCS is hiring fresh engineering graduates through its National Qualifier Test and campus recruitment process. Selected candidates will join TCS iON training and be placed across service lines including ADM, testing, and infrastructure. The role demands strong analytical and communication skills alongside foundational programming knowledge. TCS offers a structured career path with regular appraisal cycles and global mobility options."
  },
  {
    id: 5,
    title: "Junior Backend Developer",
    company: "TCS",
    location: "Hyderabad",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Java", "Spring Boot", "MySQL", "REST APIs"],
    source: "Naukri",
    postedDaysAgo: 2,
    salaryRange: "4–6 LPA",
    applyUrl: "https://www.naukri.com/job-listings/junior-backend-developer-tcs-hyderabad-3112847005",
    description: "TCS Hyderabad is hiring Junior Backend Developers to support its digital transformation projects for global enterprise clients. You will develop and maintain REST APIs using Java and Spring Boot, integrate with MySQL databases, and participate in agile ceremonies. Candidates with 0–1 years of experience and strong Java fundamentals are preferred. TCS provides learning credits and certifications as part of this role."
  },
  {
    id: 6,
    title: "QA Intern",
    company: "TCS",
    location: "Bangalore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Manual Testing", "Test Cases", "JIRA", "SQL"],
    source: "Indeed",
    postedDaysAgo: 7,
    salaryRange: "₹15k–₹25k/month",
    applyUrl: "https://in.indeed.com/viewjob?jk=tcs1234qa006",
    description: "TCS Bangalore is seeking QA Interns to join its quality assurance division. You will write and execute test cases, log defects in JIRA, and collaborate with development teams to ensure product quality. No prior testing experience is required; training will be provided. A keen eye for detail and systematic thinking are the most important qualities for this role."
  },
  {
    id: 7,
    title: "Graduate Engineer Trainee",
    company: "Wipro",
    location: "Hyderabad",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "Python", "DBMS", "Operating Systems"],
    source: "LinkedIn",
    postedDaysAgo: 4,
    salaryRange: "3.5 LPA",
    applyUrl: "https://www.linkedin.com/jobs/view/3812547007",
    description: "Wipro's Engineering Pool hiring programme selects fresh engineering graduates for its GET track. Candidates undergo training at Wipro's facility before being mapped to a vertical. The programme covers software development, cloud fundamentals, and client management. Wipro actively promotes internal mobility and offers early leadership opportunities for high performers."
  },
  {
    id: 8,
    title: "Frontend Intern",
    company: "Wipro",
    location: "Bangalore",
    mode: "Remote",
    experience: "Fresher",
    skills: ["HTML", "CSS", "JavaScript", "React"],
    source: "Naukri",
    postedDaysAgo: 6,
    salaryRange: "₹18k–₹30k/month",
    applyUrl: "https://www.naukri.com/job-listings/frontend-intern-wipro-bangalore-3112847008",
    description: "Wipro is offering a fully remote Frontend Intern role for fresh graduates with an interest in UI development. You will build responsive interfaces using React, collaborate with designers via Figma handoffs, and write clean, documented code. The internship is 6 months long with possibility of extension. Weekly sync calls with the engineering lead are part of the structure."
  },
  {
    id: 9,
    title: "Java Developer",
    company: "Wipro",
    location: "Pune",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Java", "Spring Boot", "Hibernate", "Maven"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "4–7 LPA",
    applyUrl: "https://www.linkedin.com/jobs/view/3812547009",
    description: "Wipro Pune is hiring Java Developers with 0–1 year of experience for its enterprise application delivery team. You will develop backend modules using Java and Spring Boot, write unit tests, and participate in client deliverables. Strong OOP fundamentals and familiarity with Maven build tools are required. This is a hybrid role with 2–3 office days per week."
  },
  {
    id: 10,
    title: "Junior Backend Developer",
    company: "Accenture",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Node.js", "Express", "PostgreSQL", "Docker"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "6–10 LPA",
    applyUrl: "https://www.linkedin.com/jobs/view/3812547010",
    description: "Accenture's Technology practice in Bangalore is hiring a Junior Backend Developer for its cloud modernisation delivery unit. You will build and deploy Node.js APIs, work with PostgreSQL databases, and containerise services using Docker. The team follows agile delivery with two-week sprints. Experience with cloud platforms (AWS or GCP) is a plus."
  },
  {
    id: 11,
    title: "Data Analyst Intern",
    company: "Accenture",
    location: "Gurgaon",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "Pandas", "Tableau", "SQL"],
    source: "Naukri",
    postedDaysAgo: 3,
    salaryRange: "₹20k–₹35k/month",
    applyUrl: "https://www.naukri.com/job-listings/data-analyst-intern-accenture-gurgaon-3112847011",
    description: "Accenture Gurgaon is hiring Data Analyst Interns for its Applied Intelligence practice. Interns will work alongside senior analysts on data wrangling, dashboard development, and client insight presentations. Proficiency in Python (Pandas, NumPy) and SQL is expected. Tableau training will be provided during onboarding. The internship is 6 months and can lead to a full-time analyst role."
  },
  {
    id: 12,
    title: "SDE Intern",
    company: "Accenture",
    location: "Noida",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "Spring", "Git", "Agile"],
    source: "Indeed",
    postedDaysAgo: 8,
    salaryRange: "₹18k–₹25k/month",
    applyUrl: "https://in.indeed.com/viewjob?jk=acc5678sde012",
    description: "Accenture Noida is offering SDE internships for final-year or recently graduated engineers. You will work within delivery squads, contribute to feature development, and gain exposure to enterprise-scale Java applications. Interns attend client review meetings and are encouraged to present their work. A strong academic record in Computer Science or IT is preferred."
  },
  {
    id: 13,
    title: "Graduate Engineer Trainee",
    company: "Capgemini",
    location: "Mumbai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "SQL", "Communication", "Teamwork"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "3.8 LPA",
    applyUrl: "https://www.linkedin.com/jobs/view/3812547013",
    description: "Capgemini is recruiting Graduate Engineer Trainees through its InfraEng and AppDev tracks. Shortlisted candidates will be trained at the Capgemini Learning Institute before being placed in client-facing projects. The programme emphasises practical skills, communication, and agile methodology. Capgemini offers one of the most structured campus-to-corporate programmes in the Indian IT industry."
  },
  {
    id: 14,
    title: "Java Developer",
    company: "Capgemini",
    location: "Pune",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Java", "Spring Boot", "REST", "JUnit"],
    source: "Naukri",
    postedDaysAgo: 5,
    salaryRange: "4–7 LPA",
    applyUrl: "https://www.naukri.com/job-listings/java-developer-capgemini-pune-3112847014",
    description: "Capgemini Pune requires a Java Developer with 0–1 year of experience for its BFSI delivery vertical. You will develop microservices using Spring Boot, write JUnit test cases, and coordinate with QA and DevOps teams for release management. Strong understanding of OOP and RESTful design is essential. This is a hybrid role with a permanent contract from day one."
  },
  {
    id: 15,
    title: "QA Intern",
    company: "Capgemini",
    location: "Chennai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Manual Testing", "Selenium basics", "JIRA", "Regression Testing"],
    source: "LinkedIn",
    postedDaysAgo: 9,
    salaryRange: "₹15k–₹25k/month",
    applyUrl: "https://www.linkedin.com/jobs/view/3812547015",
    description: "Capgemini Chennai is offering QA internships for fresh engineering graduates. You will learn and apply manual and semi-automated testing practices on live client applications. The role involves test case writing, defect logging, and regression execution. A basic introduction to Selenium will be part of your onboarding plan. Top interns are offered pre-placement interviews at the end of the term."
  },
  {
    id: 16,
    title: "Graduate Engineer Trainee",
    company: "Cognizant",
    location: "Chennai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "Python", "DBMS", "Agile Basics"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "3.5 LPA",
    applyUrl: "https://www.linkedin.com/jobs/view/3812547016",
    description: "Cognizant recruits fresh engineers through its GenC (Generation Cognizant) programme. Selected candidates are trained in technology, communication, and delivery practices before being mapped to a service line. Cognizant has strong practices in healthcare, banking, and retail tech verticals. GenC graduates receive formal mentoring from senior practitioners throughout their first year."
  },
  {
    id: 17,
    title: "React Developer",
    company: "Cognizant",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "Redux", "TypeScript", "REST APIs"],
    source: "Naukri",
    postedDaysAgo: 4,
    salaryRange: "7–11 LPA",
    applyUrl: "https://www.naukri.com/job-listings/react-developer-cognizant-bangalore-3112847017",
    description: "Cognizant Bangalore is hiring a React Developer with 1–3 years of experience for its digital experience practice. You will build and optimise SPA-based frontends for enterprise clients in retail and telecom. TypeScript and Redux knowledge is required. Familiarity with CI/CD pipelines and Git workflows is expected. This is a hybrid role with quarterly on-site client collaboration."
  },
  {
    id: 18,
    title: "QA Intern",
    company: "Cognizant",
    location: "Hyderabad",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Test Planning", "Selenium", "SQL", "Agile"],
    source: "Indeed",
    postedDaysAgo: 6,
    salaryRange: "₹16k–₹28k/month",
    applyUrl: "https://in.indeed.com/viewjob?jk=cog9012qa018",
    description: "Cognizant Hyderabad is accepting applications for QA Interns in its quality engineering unit. You will shadow senior testers on live projects, write test plans, and execute regression suites. Selenium training is provided in the first month. The internship spans 6 months with a structured assessment at month 3. Full-time conversion is available for top performers."
  },
  {
    id: 19,
    title: "Data Analyst Intern",
    company: "IBM",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "SQL", "IBM Cognos", "Data Visualisation"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "₹20k–₹40k/month",
    applyUrl: "https://www.linkedin.com/jobs/view/3812547019",
    description: "IBM India is hiring Data Analyst Interns for its Consulting division based in Bangalore. You will assist project teams with data extraction, transformation, and visualisation using IBM Cognos and Python. Exposure to cloud data platforms is a strong advantage. IBM fosters a learning-driven culture and provides access to its internal learning platform, SkillsBuild, for all interns."
  },
  {
    id: 20,
    title: "Python Developer",
    company: "IBM",
    location: "Hyderabad",
    mode: "Remote",
    experience: "Fresher",
    skills: ["Python", "Flask", "REST APIs", "Git"],
    source: "Naukri",
    postedDaysAgo: 1,
    salaryRange: "4–6 LPA",
    applyUrl: "https://www.naukri.com/job-listings/python-developer-ibm-hyderabad-3112847020",
    description: "IBM's Software Lab in Hyderabad is looking for a Python Developer (Fresher) to join its platform engineering team in a fully remote capacity. You will develop Flask-based microservices, write REST APIs, and contribute to automated testing pipelines. A solid understanding of Python fundamentals and Git version control is required. IBM's remote-first culture includes regular virtual team engagements and structured mentoring."
  },
  {
    id: 21,
    title: "Java Developer",
    company: "Oracle",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Java", "Oracle DB", "Spring MVC", "REST"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "5–9 LPA",
    applyUrl: "https://www.linkedin.com/jobs/view/3812547021",
    description: "Oracle India Development Centre in Bangalore is hiring a Java Developer with 0–1 year of experience. You will contribute to the development of enterprise database tooling and cloud-native applications using Java and Spring MVC. Exposure to Oracle DB or any RDBMS is expected. Oracle offers structured onboarding, certification paths, and access to the full Oracle technology stack."
  },
  {
    id: 22,
    title: "SDE Intern",
    company: "Oracle",
    location: "Hyderabad",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "Python", "Algorithms", "Data Structures"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "₹25k–₹40k/month",
    applyUrl: "https://www.linkedin.com/jobs/view/3812547022",
    description: "Oracle Hyderabad is offering a 6-month SDE internship for final-year B.Tech and M.Tech students. Interns will work on real product components under the guidance of principal engineers. Strong DSA fundamentals are required; knowledge of a second language beyond Java is appreciated. Oracle's internship programme is highly rated for its depth of technical exposure."
  },
  {
    id: 23,
    title: "Junior Backend Developer",
    company: "SAP",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Java", "SAP HANA", "Spring Boot", "Microservices"],
    source: "LinkedIn",
    postedDaysAgo: 4,
    salaryRange: "8–14 LPA",
    applyUrl: "https://www.linkedin.com/jobs/view/3812547023",
    description: "SAP Labs Bangalore is looking for a Junior Backend Developer with 1–3 years of experience to contribute to its ERP cloud platform. You will build microservices on SAP BTP, work with SAP HANA databases, and collaborate with product managers to deliver enterprise-grade features. Prior experience with SAP products is helpful but not mandatory. SAP offers generous learning budgets and 20% time for innovation projects."
  },
  {
    id: 24,
    title: "React Developer",
    company: "SAP",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "SAP Fiori", "TypeScript", "GraphQL"],
    source: "Naukri",
    postedDaysAgo: 7,
    salaryRange: "8–14 LPA",
    applyUrl: "https://www.naukri.com/job-listings/react-developer-sap-bangalore-3112847024",
    description: "SAP Labs India requires a React Developer with 1–3 years of experience for its Fiori UI platform team. You will build enterprise user interfaces using React and SAP's UI5 component library, contribute to design system documentation, and write integration tests. GraphQL API consumption experience is a significant advantage. SAP is known for its strong work-life balance and flexible work policies."
  },
  {
    id: 25,
    title: "QA Intern",
    company: "Dell",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Automation Testing", "Python", "Jenkins", "JIRA"],
    source: "LinkedIn",
    postedDaysAgo: 5,
    salaryRange: "₹20k–₹35k/month",
    applyUrl: "https://www.linkedin.com/jobs/view/3812547025",
    description: "Dell Technologies Bangalore is hiring QA Interns for its client solutions engineering team. You will write and run automated test suites in Python, log bugs in JIRA, and assist in CI/CD pipeline validation through Jenkins. Dell's QA team owns quality gates for enterprise hardware and software products. Interns are given clear ownership of at least one test module for the duration of their tenure."
  },
  {
    id: 26,
    title: "SDE Intern",
    company: "Dell",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "REST APIs", "Linux", "Bash"],
    source: "Indeed",
    postedDaysAgo: 3,
    salaryRange: "₹22k–₹40k/month",
    applyUrl: "https://in.indeed.com/viewjob?jk=dell3456sde026",
    description: "Dell Technologies is offering SDE Internships for its infrastructure software division. You will develop automation tools and REST APIs in Python, work on Linux systems, and write Bash scripts for deployment automation. The environment is collaborative and engineering-first. Interns are encouraged to present demos at the end of their internship, and outstanding candidates receive early-access return offers."
  },
  {
    id: 27,
    title: "SDE Intern",
    company: "Amazon",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Java", "Data Structures", "Algorithms", "System Design basics"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "₹60k–₹70k/month",
    applyUrl: "https://www.linkedin.com/jobs/view/3812547027",
    description: "Amazon India is hiring SDE Interns for a highly competitive 8-week summer internship programme. Interns work on real Amazon products and services, receiving the same tools and access as full-time SDEs. Strong DSA, LLD, and communication skills are essential; the bar is high. Interns who pass the midterm and final reviews receive full-time return offers. The stipend is among the highest in the industry."
  },
  {
    id: 28,
    title: "Junior Backend Developer",
    company: "Amazon",
    location: "Hyderabad",
    mode: "Onsite",
    experience: "1-3",
    skills: ["Java", "AWS", "DynamoDB", "Lambda"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "15–25 LPA",
    applyUrl: "https://www.linkedin.com/jobs/view/3812547028",
    description: "Amazon Hyderabad (development centre) is hiring Junior Backend Developers with 1–3 years of experience for its AWS-native product teams. You will design and build serverless applications using Lambda, DynamoDB, and SNS. Ownership is high — you will be expected to own services end-to-end from design to deployment. Strong Java fundamentals and familiarity with distributed systems concepts are required."
  },
  {
    id: 29,
    title: "Frontend Intern",
    company: "Flipkart",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["React", "JavaScript", "CSS", "HTML"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "₹35k–₹50k/month",
    applyUrl: "https://www.linkedin.com/jobs/view/3812547029",
    description: "Flipkart is hiring Frontend Interns to work on components used by millions of customers across its e-commerce platform. You will build and test React components, collaborate with product designers, and contribute to the Flipkart design system. The internship is 3 months long and fully integrated into the engineering team. Top interns regularly receive pre-placement offers to join Flipkart's SDE-I track."
  },
  {
    id: 30,
    title: "SDE Intern",
    company: "Flipkart",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Java", "System Design", "Data Structures", "Algorithms"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "₹50k–₹65k/month",
    applyUrl: "https://www.linkedin.com/jobs/view/3812547030",
    description: "Flipkart's internship programme is among India's most prestigious for engineering students. SDE Interns work on high-scale distributed systems that handle hundreds of thousands of transactions per second. The interview process is rigorous — DSA and system design rounds are expected. A return offer at SDE-I level is given to interns who clear the end-of-internship evaluation."
  },
  {
    id: 31,
    title: "SDE Intern",
    company: "Swiggy",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "Go basics", "Kafka", "Redis"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "₹35k–₹50k/month",
    applyUrl: "https://www.linkedin.com/jobs/view/3812547031",
    description: "Swiggy is inviting SDE Interns to join its Bangalore engineering hub for a 3-month engagement. You will work on real components within Swiggy's food delivery or commerce platform, receiving a code review from senior engineers every sprint. The environment is fast-paced and product-minded. Interns get access to all internal tools and are expected to demo their work at the end of the programme."
  },
  {
    id: 32,
    title: "Junior Backend Developer",
    company: "Swiggy",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Go", "gRPC", "PostgreSQL", "Kubernetes"],
    source: "Naukri",
    postedDaysAgo: 5,
    salaryRange: "12–18 LPA",
    applyUrl: "https://www.naukri.com/job-listings/junior-backend-developer-swiggy-bangalore-3112847032",
    description: "Swiggy's platform engineering team is looking for a Junior Backend Developer with 1–3 years of experience. You will build scalable gRPC services in Go, manage deployments on Kubernetes, and work with PostgreSQL at high throughput. Experience with distributed systems, rate limiting, and fault tolerance patterns is valued. Swiggy offers generous food credits and flexible work hours."
  },
  {
    id: 33,
    title: "React Developer",
    company: "Razorpay",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "TypeScript", "Redux Toolkit", "Jest"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "14–22 LPA",
    applyUrl: "https://www.linkedin.com/jobs/view/3812547033",
    description: "Razorpay is hiring a React Developer with 1–3 years of experience for its payments dashboard team. You will build interfaces used by thousands of merchants daily, working closely with product managers and designers. TypeScript and Redux Toolkit are the standard stack. Unit and integration testing with Jest is expected. Razorpay is known for its strong engineering culture and fast career progression."
  },
  {
    id: 34,
    title: "Python Developer",
    company: "Razorpay",
    location: "Bangalore",
    mode: "Remote",
    experience: "0-1",
    skills: ["Python", "Django", "PostgreSQL", "Redis"],
    source: "LinkedIn",
    postedDaysAgo: 6,
    salaryRange: "6–10 LPA",
    applyUrl: "https://www.linkedin.com/jobs/view/3812547034",
    description: "Razorpay is looking for a Python Developer with 0–1 year of experience to join its backend platform team remotely. You will build and maintain Django services, write clean migration scripts, and collaborate with senior engineers on database schema design. Redis caching experience is a plus. Razorpay's remote culture is well-established, with async-first communication and regular team meetups."
  },
  {
    id: 35,
    title: "Junior Backend Developer",
    company: "PhonePe",
    location: "Bangalore",
    mode: "Onsite",
    experience: "1-3",
    skills: ["Java", "Spring Boot", "Kafka", "MySQL"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "12–20 LPA",
    applyUrl: "https://www.linkedin.com/jobs/view/3812547035",
    description: "PhonePe is hiring Junior Backend Developers with 1–3 years of experience for its payments infrastructure team. You will develop high-throughput Java services, work with Kafka event streams, and maintain MySQL databases under strict SLAs. PhonePe processes over 500 million transactions per month — the scale is real. The team is onsite-first with strong cross-functional collaboration."
  },
  {
    id: 36,
    title: "Frontend Intern",
    company: "PhonePe",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["React", "JavaScript", "REST APIs", "Figma"],
    source: "Naukri",
    postedDaysAgo: 8,
    salaryRange: "₹30k–₹50k/month",
    applyUrl: "https://www.naukri.com/job-listings/frontend-intern-phonepe-bangalore-3112847036",
    description: "PhonePe is offering a Frontend Internship for engineering students or recent graduates passionate about building intuitive fintech interfaces. You will implement UI components in React, consume REST APIs, and work from Figma designs provided by PhonePe's product design team. The internship is 3 months with a possible extension. Conversion to SDE-I is available based on performance review."
  },
  {
    id: 37,
    title: "Data Analyst Intern",
    company: "Paytm",
    location: "Noida",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["SQL", "Python", "Looker", "A/B Testing basics"],
    source: "LinkedIn",
    postedDaysAgo: 4,
    salaryRange: "₹18k–₹30k/month",
    applyUrl: "https://www.linkedin.com/jobs/view/3812547037",
    description: "Paytm is hiring Data Analyst Interns at its Noida headquarters for its growth analytics team. You will build SQL queries to analyse transaction and user behaviour data, build Looker dashboards, and assist product teams with A/B test readouts. This is a high-exposure role with direct stakeholder visibility. Strong SQL skills and logical thinking are non-negotiable."
  },
  {
    id: 38,
    title: "QA Intern",
    company: "Paytm",
    location: "Noida",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Postman", "Manual Testing", "API Testing", "Regression"],
    source: "Naukri",
    postedDaysAgo: 9,
    salaryRange: "₹15k–₹25k/month",
    applyUrl: "https://www.naukri.com/job-listings/qa-intern-paytm-noida-3112847038",
    description: "Paytm's QA team is seeking interns with a strong attention to detail to join its testing division in Noida. Interns will conduct manual API testing using Postman, write regression test suites, and report bugs in a structured format. The environment is fast-moving; you will test multiple builds per week. Paytm's QA team is known for its culture of ownership and quality-first thinking."
  },
  {
    id: 39,
    title: "SDE Intern",
    company: "Zoho",
    location: "Chennai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "JavaScript", "MySQL", "OOP"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "₹20k–₹30k/month",
    applyUrl: "https://www.linkedin.com/jobs/view/3812547039",
    description: "Zoho Corporation is hiring SDE Interns for its Chennai office across multiple product teams. You will contribute to Zoho's suite of SaaS applications — CRM, Books, Desk, or Projects — under the mentorship of experienced engineers. Zoho builds almost everything in-house and has a strong culture of craftsmanship. Interns are evaluated for a direct PPO at the end of a successful 6-month stint."
  },
  {
    id: 40,
    title: "Java Developer",
    company: "Zoho",
    location: "Chennai",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Java", "MySQL", "Servlets", "OOPS"],
    source: "Naukri",
    postedDaysAgo: 6,
    salaryRange: "4–8 LPA",
    applyUrl: "https://www.naukri.com/job-listings/java-developer-zoho-chennai-3112847040",
    description: "Zoho is hiring Java Developers with 0–1 year of experience for its core product engineering team. You will build server-side features for Zoho's cloud applications using Java and MySQL. Zoho has a strong preference for engineers with solid fundamentals over framework familiarity. The interview process is technically demanding and highly respected in the industry. Zoho offers lifetime employment culture and strong non-equity benefits."
  },
  {
    id: 41,
    title: "React Developer",
    company: "Freshworks",
    location: "Chennai",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "JavaScript", "REST APIs", "CSS-in-JS"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "12–18 LPA",
    applyUrl: "https://www.linkedin.com/jobs/view/3812547041",
    description: "Freshworks is hiring a React Developer with 1–3 years of experience for its product engineering team working on Freshdesk. You will develop customer-facing UI components, contribute to the Freshworks component library, and collaborate with UX designers on interaction design decisions. A strong portfolio of well-written React code is expected. Freshworks promotes a diverse, globally connected engineering culture from its Chennai headquarters."
  },
  {
    id: 42,
    title: "QA Intern",
    company: "Freshworks",
    location: "Chennai",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Selenium", "Python", "Test Automation", "Agile"],
    source: "Naukri",
    postedDaysAgo: 7,
    salaryRange: "₹18k–₹30k/month",
    applyUrl: "https://www.naukri.com/job-listings/qa-intern-freshworks-chennai-3112847042",
    description: "Freshworks is looking for QA Interns to join its SDET team in Chennai. You will write automated tests using Selenium and Python, maintain test pipelines, and participate in agile sprint ceremonies. Freshworks places interns on real product teams from day one. The internship is 6 months, and high-performing interns are offered SDET-1 roles at the conclusion of the programme."
  },
  {
    id: 43,
    title: "Junior Backend Developer",
    company: "Juspay",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Haskell", "PureScript", "PostgreSQL", "Microservices"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "10–16 LPA",
    applyUrl: "https://www.linkedin.com/jobs/view/3812547043",
    description: "Juspay, India's leading payments orchestration layer, is hiring a Junior Backend Developer for its core payments engine team. The stack is functional — Haskell and PureScript — which is unusual and rewarding. You will contribute to payment routing logic, ensure fault tolerance in transaction flows, and write property-based tests. Prior FP experience is preferred but curiosity and aptitude are equally weighted."
  },
  {
    id: 44,
    title: "Frontend Intern",
    company: "Juspay",
    location: "Bangalore",
    mode: "Remote",
    experience: "Fresher",
    skills: ["PureScript", "React", "JavaScript", "Functional Programming"],
    source: "LinkedIn",
    postedDaysAgo: 4,
    salaryRange: "₹20k–₹35k/month",
    applyUrl: "https://www.linkedin.com/jobs/view/3812547044",
    description: "Juspay is hiring remote Frontend Interns interested in functional programming and UI development. The team uses PureScript compiled to JavaScript for its checkout SDK. You will contribute to UI components used by millions of payment flows daily. Willingness to learn functional programming fundamentals is the most important requirement. Juspay provides comprehensive onboarding and a dedicated mentor for the duration of the internship."
  },
  {
    id: 45,
    title: "SDE Intern",
    company: "CRED",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Kotlin", "Java", "REST APIs", "System Design"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "₹50k–₹70k/month",
    applyUrl: "https://www.linkedin.com/jobs/view/3812547045",
    description: "CRED offers one of the most coveted engineering internships in India, with a stipend matching several full-time offers. Interns work on backend services powering India's premium credit card management platform. Ownership is high from week one — you will own a feature end-to-end. The bar for interview selection is extremely high; prior competitive programming or open-source contributions are a strong positive signal."
  },
  {
    id: 46,
    title: "Data Analyst Intern",
    company: "CRED",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["SQL", "Python", "Amplitude", "Product Analytics"],
    source: "Naukri",
    postedDaysAgo: 5,
    salaryRange: "₹30k–₹50k/month",
    applyUrl: "https://www.naukri.com/job-listings/data-analyst-intern-cred-bangalore-3112847046",
    description: "CRED's data team is hiring a Data Analyst Intern to work closely with its product and growth teams in Bangalore. You will build SQL-based analytics pipelines, instrument events in Amplitude, and generate actionable insights for leadership. Strong communication skills are as important as technical ability — you will present findings weekly to senior PMs. CRED's premium member data offers a rare analytics experience."
  },
  {
    id: 47,
    title: "SDE Intern",
    company: "BrowserStack",
    location: "Mumbai",
    mode: "Remote",
    experience: "Fresher",
    skills: ["Ruby", "JavaScript", "Testing Frameworks", "Git"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "₹35k–₹50k/month",
    applyUrl: "https://www.linkedin.com/jobs/view/3812547047",
    description: "BrowserStack is hiring SDE Interns for a fully remote engagement from its Mumbai entity. You will contribute to testing infrastructure used by engineers at Google, Microsoft, and Airbnb. The stack includes Ruby, JavaScript, and custom testing frameworks. BrowserStack has a global remote culture with async-first communication and regular virtual events. The intern programme is designed to simulate the full-time SDE experience."
  },
  {
    id: 48,
    title: "Junior Backend Developer",
    company: "BrowserStack",
    location: "Mumbai",
    mode: "Remote",
    experience: "1-3",
    skills: ["Ruby on Rails", "PostgreSQL", "Redis", "Sidekiq"],
    source: "LinkedIn",
    postedDaysAgo: 6,
    salaryRange: "10–15 LPA",
    applyUrl: "https://www.linkedin.com/jobs/view/3812547048",
    description: "BrowserStack is hiring a Junior Backend Developer with 1–3 years of experience for its platform team, fully remote. You will build and maintain Rails services, manage background jobs with Sidekiq, and optimise PostgreSQL queries for developer-facing APIs. BrowserStack's infrastructure is used by 50,000+ companies globally — quality and reliability are paramount. The company is known for strong compensation and work autonomy."
  },
  {
    id: 49,
    title: "Junior Backend Developer",
    company: "Groww",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Java", "Spring Boot", "Kafka", "AWS"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "12–18 LPA",
    applyUrl: "https://www.linkedin.com/jobs/view/3812547049",
    description: "Groww, India's fastest-growing investment platform, is hiring Junior Backend Developers for its Bangalore engineering hub. You will build and scale Java-based microservices on AWS, process financial event streams with Kafka, and contribute to Groww's zero-downtime deployment culture. The platform serves 10 million+ active investors. A strong understanding of eventual consistency and distributed transactions is valued."
  },
  {
    id: 50,
    title: "Frontend Intern",
    company: "Meesho",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["React", "JavaScript", "CSS Modules", "REST APIs"],
    source: "Naukri",
    postedDaysAgo: 7,
    salaryRange: "₹25k–₹40k/month",
    applyUrl: "https://www.naukri.com/job-listings/frontend-intern-meesho-bangalore-3112847050",
    description: "Meesho is looking for Frontend Interns to work on its social commerce platform serving Tier 2 and Tier 3 India. You will build low-bandwidth-optimised React components, work from detailed Figma specs, and collaborate with product managers on UX decisions. Meesho's tech stack focuses on performance at constraint. The intern will have direct visibility with the frontend engineering lead."
  },
  {
    id: 51,
    title: "Python Developer",
    company: "Zerodha",
    location: "Bangalore",
    mode: "Remote",
    experience: "0-1",
    skills: ["Python", "FastAPI", "PostgreSQL", "Redis"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "5–9 LPA",
    applyUrl: "https://www.linkedin.com/jobs/view/3812547051",
    description: "Zerodha, India's largest retail stock broker by volume, is hiring a Python Developer with 0–1 year of experience for its remote engineering team. You will build and maintain FastAPI services that power Zerodha's trading and portfolio APIs. PostgreSQL and Redis form the data layer. Zerodha values engineers who write simple, correct code over engineers who chase complexity. The team is small, senior, and flat."
  },
  {
    id: 52,
    title: "React Developer",
    company: "ShareChat",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "Redux", "JavaScript", "Performance Optimisation"],
    source: "LinkedIn",
    postedDaysAgo: 4,
    salaryRange: "10–16 LPA",
    applyUrl: "https://www.linkedin.com/jobs/view/3812547052",
    description: "ShareChat is hiring a React Developer with 1–3 years of experience for its web platform team. You will build performance-critical UI features for a social media platform with 200 million users. Redux state management and advanced JavaScript patterns are the daily toolkit. ShareChat offers equity as part of compensation and has a fast-paced, startup-energy culture despite its scale."
  },
  {
    id: 53,
    title: "SDE Intern",
    company: "Urban Company",
    location: "Gurgaon",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Node.js", "MongoDB", "REST APIs", "JavaScript"],
    source: "LinkedIn",
    postedDaysAgo: 5,
    salaryRange: "₹25k–₹40k/month",
    applyUrl: "https://www.linkedin.com/jobs/view/3812547053",
    description: "Urban Company is hiring SDE Interns for its Gurgaon office to work on its home services marketplace platform. You will develop Node.js APIs, work with MongoDB collections, and contribute to features used by service professionals and customers alike. The team is cross-functional, and interns collaborate with product, design, and business teams. Urban Company has a strong culture of mentorship and rapid learning."
  },
  {
    id: 54,
    title: "Junior Backend Developer",
    company: "Postman",
    location: "Bangalore",
    mode: "Remote",
    experience: "1-3",
    skills: ["Node.js", "Express", "MongoDB", "API Design"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "15–22 LPA",
    applyUrl: "https://www.linkedin.com/jobs/view/3812547054",
    description: "Postman, the world's leading API platform, is hiring a Junior Backend Developer for its remote-first engineering team. You will build backend services that power Postman's collaboration and testing infrastructure. Node.js and Express are the primary stack; MongoDB handles document storage. API design literacy is genuinely useful here — you are building a platform for API developers. Postman offers competitive global compensation and strong async culture."
  },
  {
    id: 55,
    title: "React Developer",
    company: "Darwinbox",
    location: "Hyderabad",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "JavaScript", "Redux", "Ant Design"],
    source: "LinkedIn",
    postedDaysAgo: 6,
    salaryRange: "8–13 LPA",
    applyUrl: "https://www.linkedin.com/jobs/view/3812547055",
    description: "Darwinbox, Asia's fastest-growing HR tech platform, is hiring a React Developer with 1–3 years of experience. You will work on Darwinbox's enterprise HRMS product, building complex form-driven UI workflows using React and Ant Design. Redux state management and RESTful API integration are daily work. Darwinbox is growing rapidly, and internal mobility opportunities are significant."
  },
  {
    id: 56,
    title: "Java Developer",
    company: "LeadSquared",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Java", "Spring Boot", "MySQL", "Microservices"],
    source: "Naukri",
    postedDaysAgo: 2,
    salaryRange: "4–8 LPA",
    applyUrl: "https://www.naukri.com/job-listings/java-developer-leadsquared-bangalore-3112847056",
    description: "LeadSquared, a leading CRM and marketing automation company, is hiring a Java Developer with 0–1 year of experience. You will build backend features for LeadSquared's sales platform using Spring Boot and MySQL. The team follows a microservices architecture with high code review standards. LeadSquared has a strong engineering culture with quarterly hackathons and dedicated learning time each week."
  },
  {
    id: 57,
    title: "SDE Intern",
    company: "Chargebee",
    location: "Chennai",
    mode: "Remote",
    experience: "Fresher",
    skills: ["Java", "Python", "REST APIs", "Webhooks"],
    source: "LinkedIn",
    postedDaysAgo: 4,
    salaryRange: "₹30k–₹50k/month",
    applyUrl: "https://www.linkedin.com/jobs/view/3812547057",
    description: "Chargebee, the global subscription billing leader, is offering remote SDE Internships from its Chennai entity. You will build webhook handlers, contribute to billing engine features, and write integration tests for third-party payment gateways. Chargebee's API-first culture means you will write clean, well-documented code from the very beginning. The internship has a strong PPO pipeline for top performers."
  },
  {
    id: 58,
    title: "Data Analyst Intern",
    company: "Nykaa",
    location: "Mumbai",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["SQL", "Python", "Google Analytics", "Tableau"],
    source: "LinkedIn",
    postedDaysAgo: 8,
    salaryRange: "₹18k–₹30k/month",
    applyUrl: "https://www.linkedin.com/jobs/view/3812547058",
    description: "Nykaa's digital analytics team is hiring Data Analyst Interns to join its Mumbai e-commerce intelligence function. You will analyse customer journey data, build Tableau dashboards for the product and growth teams, and present weekly cohort analysis to senior leadership. Experience with Google Analytics or GA4 is a meaningful plus. Nykaa offers a deeply collaborative, consumer-brand-first culture."
  },
  {
    id: 59,
    title: "Python Developer",
    company: "Ola",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Python", "Django", "MySQL", "Celery"],
    source: "Naukri",
    postedDaysAgo: 3,
    salaryRange: "5–9 LPA",
    applyUrl: "https://www.naukri.com/job-listings/python-developer-ola-bangalore-3112847059",
    description: "Ola is hiring Python Developers with 0–1 year of experience to join its mobility engineering team in Bangalore. You will develop Django services for driver and ride management, schedule background tasks with Celery, and work on integrations with third-party map and payment providers. Ola's environment is fast-paced with frequent deployments. Experience with async Python or geospatial libraries is a bonus."
  },
  {
    id: 60,
    title: "QA Intern",
    company: "MakeMyTrip",
    location: "Gurgaon",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Selenium", "Java", "TestNG", "JIRA"],
    source: "Indeed",
    postedDaysAgo: 10,
    salaryRange: "₹15k–₹25k/month",
    applyUrl: "https://in.indeed.com/viewjob?jk=mmt7890qa060",
    description: "MakeMyTrip is hiring QA Interns for its quality engineering division based in Gurgaon. You will develop and run Selenium-based automated tests for flight, hotel, and holiday booking flows using Java and TestNG. Defects are tracked in JIRA with detailed reproduction steps. MakeMyTrip's QA team has a well-defined testing pyramid, and interns contribute meaningfully to all three levels."
  }
];
